# -*- coding: utf-8 -*-
"""AS Pit escape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjk7lh1Ze6KcPd3M6rVyyXZvpFwfpSnd
"""

from controller import Robot

robot = Robot()

timestep = int(robot.getBasicTimeStep())

# Max possible speed for the motor of the robot.
maxSpeed = 8.72

gyro = robot.getGyro("body gyro")

print(gyro.getValues())

maxv = 0




# Configuration of the main motor of the robot.
pitchMotor = robot.getMotor("body pitch motor")
pitchMotor.setPosition(float('inf'))
pitchMotor.setVelocity(0.0)

# This is the time interval between direction switches.
# The robot will start by going forward and will go backward after
# this time interval, and so on.
timeInterval = 1.5

# At first we go forward.
pitchMotor.setVelocity(maxSpeed)
forward = True
lastTime = 0

while robot.step(timestep) != -1:
    gyro = robot.getGyro("body gyro")
    gyro.enable(timestep)
    print(gyro.getValues()[1])
    x = gyro.getValues()[0]
    y = gyro.getValues()[1]
    z = gyro.getValues()[2]
    av = x+y+z/3
    #print(av)
    if -0.05 <= av <= 0.05:
        # If yes, then we switch directions.
        if forward:
            pitchMotor.setVelocity(-maxSpeed)
        else:
            pitchMotor.setVelocity(maxSpeed)
        forward = not forward
        lastTime = now
    
    
    now = robot.getTime()
    # We check if enough time has elapsed.
    #if now - lastTime > timeInterval: